name: Build web

on:
  push:
    tags:
      - "v*"

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Download wing vendor
        run: |
          git submodule update --init --recursive
          cd wing
          export GOMODCACHE="${PWD}"/go-mod
          go mod download -modcacherw
          cd dae-core && go mod download -modcacherw && cd ..
          find "$GOMODCACHE" -maxdepth 1 ! -name "cache" ! -name "go-mod" -exec sudo rm -rf {} \;

      - name: Create full source ZIP archive and Signature
        run: |
          zip -9vr daed-full-src.zip . -x .git/\\*

      - name: Build web
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build --filter daed
          mv apps/web/dist web

      - name: Zip web artifact
        run: zip -r web.zip ./web

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          prerelease: false
          artifacts: |
            daed-full-src.zip
            web.zip
