name: Build web

on:
  push:
    tags:
      - "v*"

env:
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Build web
        env:
          NODE_OPTIONS: --max-old-space-size=4096
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build --filter daed
          mv apps/web/dist web

      - name: Zip web artifact
        run: zip -r web.zip ./web

      - name: Upload packages
        uses: ncipollo/release-action@v1
        with:
          name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
          replacesArtifacts: true
          prerelease: false
          artifacts: web.zip
